services:
  postgres:
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac_pass
    volumes:
      - ./test/01-prac.init.sql:/docker-entrypoint-initdb.d/01-prac.init.sql
      - ./test/02-prac.films.sql:/docker-entrypoint-initdb.d/02-prac.films.sql
      - ./test/03-prac.schedules.sql:/docker-entrypoint-initdb.d/03-prac.schedules.sql